
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: eunchan
    password: elastic-search
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: info